import asyncio
import os
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import SessionLocal
from app.models import ModelCatalog


MOCK_CATALOG_ITEMS: list[dict[str, Any]] = [
    {
        "provider": "mock",
        "model_code": "mock-chat",
        "display_name": "Mock Chat",
        "model_type": "llm",
        "description": "仅用于离线演示的 Mock 对话模型，生产模式不会参与真实路由。",
        "context_window": 4096,
        "supports_streaming": True,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "mock://local",
        "protocol": "mock",
        "recommended_parameters": {
            "temperature": 0.2,
            "max_tokens": 512,
            "availability": "demo_only",
            "is_demo": True,
        },
        "official_url": None,
        "pricing": {"status": "free_local"},
        "icon": "mock",
        "sort_order": 10,
        "is_active": True,
    },
    {
        "provider": "mock",
        "model_code": "mock-embedding",
        "display_name": "Mock Embedding",
        "model_type": "embedding",
        "description": "仅用于离线演示的 Mock 向量模型，生产模式不会参与真实路由。",
        "context_window": 8192,
        "supports_streaming": False,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "mock://local",
        "protocol": "mock",
        "recommended_parameters": {
            "dimensions": 1536,
            "availability": "demo_only",
            "is_demo": True,
        },
        "official_url": None,
        "pricing": {"status": "free_local"},
        "icon": "mock",
        "sort_order": 11,
        "is_active": True,
    },
]


CATALOG_ONLY_TYPES = {"rerank", "vision", "asr", "tts", "image"}


def catalog_item(
    *,
    provider: str,
    model_code: str,
    display_name: str,
    model_type: str,
    description: str,
    context_window: int | None,
    supports_streaming: bool,
    supports_tools: bool,
    supports_vision: bool,
    default_base_url: str,
    protocol: str,
    recommended_parameters: dict[str, Any] | None = None,
    official_url: str,
    pricing: dict[str, Any] | None = None,
    icon: str | None = None,
    sort_order: int,
    is_active: bool = True,
) -> dict[str, Any]:
    parameters = dict(recommended_parameters or {})
    if model_type in CATALOG_ONLY_TYPES:
        parameters["availability"] = "catalog_only"
    else:
        parameters.setdefault("availability", "needs_real_key")
    return {
        "provider": provider,
        "model_code": model_code,
        "display_name": display_name,
        "model_type": model_type,
        "description": description,
        "context_window": context_window,
        "supports_streaming": supports_streaming,
        "supports_tools": supports_tools,
        "supports_vision": supports_vision,
        "default_base_url": default_base_url,
        "protocol": protocol,
        "recommended_parameters": parameters,
        "official_url": official_url,
        "pricing": pricing or {"status": "see_official"},
        "icon": icon or provider,
        "sort_order": sort_order,
        "is_active": is_active,
    }


REAL_CATALOG_ITEMS: list[dict[str, Any]] = [
    {
        "provider": "deepseek",
        "model_code": "deepseek-chat",
        "display_name": "DeepSeek Chat",
        "model_type": "llm",
        "description": "DeepSeek 通用对话模型，已收录待用户使用真实 API Key 实测。",
        "context_window": 64000,
        "supports_streaming": True,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "https://api.deepseek.com",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "temperature": 0.7,
            "max_tokens": 2048,
            "availability": "needs_real_key",
        },
        "official_url": "https://api-docs.deepseek.com/",
        "pricing": {"status": "see_official"},
        "icon": "deepseek",
        "sort_order": 20,
        "is_active": True,
    },
    {
        "provider": "deepseek",
        "model_code": "deepseek-reasoner",
        "display_name": "DeepSeek Reasoner",
        "model_type": "llm",
        "description": "DeepSeek 推理模型，已收录待用户使用真实 API Key 实测。",
        "context_window": 64000,
        "supports_streaming": True,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "https://api.deepseek.com",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "temperature": 0.6,
            "max_tokens": 4096,
            "availability": "needs_real_key",
        },
        "official_url": "https://api-docs.deepseek.com/",
        "pricing": {"status": "see_official"},
        "icon": "deepseek",
        "sort_order": 21,
        "is_active": True,
    },
    {
        "provider": "openai",
        "model_code": "gpt-4o-mini",
        "display_name": "GPT-4o mini",
        "model_type": "llm",
        "description": "OpenAI 轻量通用对话模型，已收录待用户使用真实 API Key 实测。",
        "context_window": 128000,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_vision": True,
        "default_base_url": "https://api.openai.com",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "temperature": 0.7,
            "max_tokens": 2048,
            "availability": "needs_real_key",
        },
        "official_url": "https://platform.openai.com/docs/models",
        "pricing": {"status": "see_official"},
        "icon": "openai",
        "sort_order": 30,
        "is_active": True,
    },
    {
        "provider": "openai",
        "model_code": "text-embedding-3-small",
        "display_name": "text-embedding-3-small",
        "model_type": "embedding",
        "description": "OpenAI 小型向量模型，已收录待用户使用真实 API Key 实测。",
        "context_window": 8191,
        "supports_streaming": False,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "https://api.openai.com",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "dimensions": 1536,
            "availability": "needs_real_key",
        },
        "official_url": "https://platform.openai.com/docs/models",
        "pricing": {"status": "see_official"},
        "icon": "openai",
        "sort_order": 31,
        "is_active": True,
    },
    {
        "provider": "openai",
        "model_code": "text-embedding-3-large",
        "display_name": "text-embedding-3-large",
        "model_type": "embedding",
        "description": "OpenAI 大型向量模型，默认 3072 维，适合更高召回质量场景。",
        "context_window": 8191,
        "supports_streaming": False,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "https://api.openai.com",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "dimensions": 3072,
            "availability": "needs_real_key",
        },
        "official_url": "https://platform.openai.com/docs/models",
        "pricing": {"status": "see_official"},
        "icon": "openai",
        "sort_order": 32,
        "is_active": True,
    },
    {
        "provider": "bge",
        "model_code": "bge-large-zh",
        "display_name": "BGE-large-zh",
        "model_type": "embedding",
        "description": "中文 BGE-large-zh 向量模型，常见输出维度为 1024。请接入 OpenAI 兼容的本地或私有 embedding 服务。",
        "context_window": 512,
        "supports_streaming": False,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "http://host.docker.internal:8000",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "dimensions": 1024,
            "availability": "needs_real_key",
        },
        "official_url": "https://huggingface.co/BAAI/bge-large-zh",
        "pricing": {"status": "self_hosted"},
        "icon": "bge",
        "sort_order": 33,
        "is_active": True,
    },
    {
        "provider": "qwen",
        "model_code": "qwen-plus",
        "display_name": "通义千问 Plus",
        "model_type": "llm",
        "description": "通义千问 Plus，DashScope OpenAI 兼容模式，已收录待用户使用真实 API Key 实测。",
        "context_window": 131072,
        "supports_streaming": True,
        "supports_tools": True,
        "supports_vision": False,
        "default_base_url": "https://dashscope.aliyuncs.com/compatible-mode",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "temperature": 0.7,
            "max_tokens": 2048,
            "availability": "needs_real_key",
        },
        "official_url": "https://help.aliyun.com/zh/model-studio/",
        "pricing": {"status": "see_official"},
        "icon": "qwen",
        "sort_order": 40,
        "is_active": True,
    },
    {
        "provider": "qwen",
        "model_code": "text-embedding-v4",
        "display_name": "通义 text-embedding-v4",
        "model_type": "embedding",
        "description": "通义千问文本向量模型，DashScope OpenAI 兼容模式，预置 dimensions=1536，可按知识库维度扩展。",
        "context_window": 8192,
        "supports_streaming": False,
        "supports_tools": False,
        "supports_vision": False,
        "default_base_url": "https://dashscope.aliyuncs.com/compatible-mode",
        "protocol": "openai_compatible",
        "recommended_parameters": {
            "dimensions": 1536,
            "availability": "needs_real_key",
        },
        "official_url": "https://help.aliyun.com/zh/model-studio/embedding-interfaces-compatible-with-openai",
        "pricing": {"status": "see_official"},
        "icon": "qwen",
        "sort_order": 41,
        "is_active": True,
    },
    catalog_item(
        provider="zhipu",
        model_code="glm-4-plus",
        display_name="GLM-4-Plus",
        model_type="llm",
        description="智谱旗舰对话模型，适合中文办公、知识问答和复杂任务处理。",
        context_window=128000,
        supports_streaming=True,
        supports_tools=True,
        supports_vision=False,
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://docs.z.ai/",
        sort_order=50,
    ),
    catalog_item(
        provider="zhipu",
        model_code="glm-4v-plus",
        display_name="GLM-4V-Plus",
        model_type="vision",
        description="智谱视觉多模态模型，适合理解图片内容并进行图文问答。",
        context_window=64000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=True,
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        protocol="openai_compatible",
        official_url="https://docs.z.ai/",
        sort_order=51,
    ),
    catalog_item(
        provider="zhipu",
        model_code="embedding-3",
        display_name="Embedding-3",
        model_type="embedding",
        description="智谱文本向量模型，适合中文知识库检索和语义匹配。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 2048},
        official_url="https://docs.z.ai/",
        sort_order=52,
    ),
    catalog_item(
        provider="zhipu",
        model_code="cogview-3",
        display_name="CogView-3",
        model_type="image",
        description="智谱图像生成模型，适合根据文字描述生成视觉素材。",
        context_window=None,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://open.bigmodel.cn/api/paas/v4",
        protocol="provider_native",
        official_url="https://docs.z.ai/",
        sort_order=53,
    ),
    catalog_item(
        provider="moonshot",
        model_code="moonshot-v1-32k",
        display_name="Moonshot v1 32K",
        model_type="llm",
        description="月之暗面 Kimi 对话模型，适合长文本阅读、总结和知识型问答。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.moonshot.ai/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://platform.kimi.ai/docs",
        sort_order=60,
    ),
    catalog_item(
        provider="moonshot",
        model_code="moonshot-v1-128k",
        display_name="Moonshot v1 128K",
        model_type="llm",
        description="月之暗面长上下文对话模型，适合处理大篇幅资料和多轮分析。",
        context_window=128000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.moonshot.ai/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://platform.kimi.ai/docs",
        sort_order=61,
    ),
    catalog_item(
        provider="baichuan",
        model_code="baichuan4-turbo",
        display_name="Baichuan4 Turbo",
        model_type="llm",
        description="百川高性能对话模型，适合中文知识问答、内容生成和办公场景。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.baichuan-ai.com/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://platform.baichuan-ai.com/docs/api",
        sort_order=70,
    ),
    catalog_item(
        provider="baichuan",
        model_code="baichuan-text-embedding",
        display_name="Baichuan Text Embedding",
        model_type="embedding",
        description="百川文本向量模型，适合构建中文知识库检索能力。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.baichuan-ai.com/v1",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 1024},
        official_url="https://platform.baichuan-ai.com/docs/api",
        sort_order=71,
    ),
    catalog_item(
        provider="iflytek",
        model_code="spark-max",
        display_name="讯飞星火 Max",
        model_type="llm",
        description="讯飞星火旗舰对话模型，适合中文办公、问答和复杂文本处理。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://spark-api-open.xf-yun.com/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://www.xfyun.cn/doc/spark/HTTP调用文档.html",
        sort_order=80,
    ),
    catalog_item(
        provider="iflytek",
        model_code="spark-asr",
        display_name="讯飞星火 ASR",
        model_type="asr",
        description="讯飞语音识别能力，适合把会议、客服和录音内容转为文本。",
        context_window=None,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.xfyun.cn",
        protocol="provider_native",
        official_url="https://www.xfyun.cn/doc/",
        sort_order=81,
    ),
    catalog_item(
        provider="iflytek",
        model_code="spark-tts",
        display_name="讯飞星火 TTS",
        model_type="tts",
        description="讯飞语音合成能力，适合把文本转为自然语音播报。",
        context_window=None,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.xfyun.cn",
        protocol="provider_native",
        official_url="https://www.xfyun.cn/doc/",
        sort_order=82,
    ),
    catalog_item(
        provider="minimax",
        model_code="abab6.5s-chat",
        display_name="abab6.5s Chat",
        model_type="llm",
        description="MiniMax 通用对话模型，适合内容生成、角色对话和多轮问答。",
        context_window=245000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.minimax.io/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://platform.minimax.io/docs",
        sort_order=90,
    ),
    catalog_item(
        provider="minimax",
        model_code="speech-01",
        display_name="MiniMax Speech-01",
        model_type="tts",
        description="MiniMax 语音合成模型，适合生成自然流畅的中文语音。",
        context_window=None,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.minimax.io/v1",
        protocol="provider_native",
        official_url="https://platform.minimax.io/docs",
        sort_order=91,
    ),
    catalog_item(
        provider="baidu",
        model_code="ernie-4.0-turbo",
        display_name="ERNIE 4.0 Turbo",
        model_type="llm",
        description="百度文心旗舰对话模型，适合企业知识问答、内容生成和办公助手。",
        context_window=128000,
        supports_streaming=True,
        supports_tools=True,
        supports_vision=False,
        default_base_url="https://qianfan.baidubce.com/v2",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://cloud.baidu.com/doc/qianfan/index.html",
        sort_order=100,
    ),
    catalog_item(
        provider="baidu",
        model_code="ernie-embedding-v1",
        display_name="ERNIE Embedding V1",
        model_type="embedding",
        description="百度文心文本向量模型，适合知识库检索和语义相似度计算。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://qianfan.baidubce.com/v2",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 384},
        official_url="https://cloud.baidu.com/doc/qianfan/index.html",
        sort_order=101,
    ),
    catalog_item(
        provider="baidu",
        model_code="ernie-irag",
        display_name="ERNIE iRAG",
        model_type="image",
        description="百度文心图像生成能力，适合按业务描述生成营销和创意素材。",
        context_window=None,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://qianfan.baidubce.com",
        protocol="provider_native",
        official_url="https://cloud.baidu.com/doc/qianfan/index.html",
        sort_order=102,
    ),
    catalog_item(
        provider="volcengine",
        model_code="doubao-pro-32k",
        display_name="豆包 Pro 32K",
        model_type="llm",
        description="火山方舟豆包对话模型，适合中文办公、问答和内容生成。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=True,
        supports_vision=False,
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://www.volcengine.com/docs/82379",
        sort_order=110,
    ),
    catalog_item(
        provider="volcengine",
        model_code="doubao-embedding",
        display_name="豆包 Embedding",
        model_type="embedding",
        description="火山方舟豆包向量模型，适合企业资料检索和语义匹配。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 2048},
        official_url="https://www.volcengine.com/docs/82379",
        sort_order=111,
    ),
    catalog_item(
        provider="volcengine",
        model_code="doubao-vision",
        display_name="豆包 Vision",
        model_type="vision",
        description="火山方舟豆包视觉多模态能力，适合理解图片内容和图文问答。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=True,
        default_base_url="https://ark.cn-beijing.volces.com/api/v3",
        protocol="openai_compatible",
        official_url="https://www.volcengine.com/docs/82379",
        sort_order=112,
    ),
    catalog_item(
        provider="tencent",
        model_code="hunyuan-turbo",
        display_name="混元 Turbo",
        model_type="llm",
        description="腾讯混元高效对话模型，适合企业办公、问答和内容生成。",
        context_window=32000,
        supports_streaming=True,
        supports_tools=True,
        supports_vision=False,
        default_base_url="https://api.hunyuan.cloud.tencent.com/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://cloud.tencent.com/document/product/1729/111007",
        sort_order=120,
    ),
    catalog_item(
        provider="tencent",
        model_code="hunyuan-embedding",
        display_name="混元 Embedding",
        model_type="embedding",
        description="腾讯混元文本向量模型，适合知识库检索和语义匹配。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.hunyuan.cloud.tencent.com/v1",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 1024},
        official_url="https://cloud.tencent.com/document/product/1729/111007",
        sort_order=121,
    ),
    catalog_item(
        provider="siliconflow",
        model_code="bce-reranker",
        display_name="BCE Reranker",
        model_type="rerank",
        description="硅基流动聚合的重排模型，适合提升知识库检索结果排序质量。",
        context_window=512,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.siliconflow.cn/v1",
        protocol="openai_compatible",
        official_url="https://docs.siliconflow.cn/",
        pricing={"status": "see_official"},
        sort_order=130,
    ),
    catalog_item(
        provider="siliconflow",
        model_code="flux-1",
        display_name="FLUX.1",
        model_type="image",
        description="硅基流动聚合的图像生成模型，适合根据文字生成高质量图片素材。",
        context_window=None,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="https://api.siliconflow.cn/v1",
        protocol="openai_compatible",
        official_url="https://docs.siliconflow.cn/",
        pricing={"status": "see_official"},
        sort_order=131,
    ),
    catalog_item(
        provider="ollama",
        model_code="llama3.1",
        display_name="Llama 3.1",
        model_type="llm",
        description="Ollama 本地对话模型，适合私有化部署和离线推理场景。",
        context_window=128000,
        supports_streaming=True,
        supports_tools=False,
        supports_vision=False,
        default_base_url="http://localhost:11434/v1",
        protocol="openai_compatible",
        recommended_parameters={"temperature": 0.7, "max_tokens": 4096},
        official_url="https://docs.ollama.com/api/openai-compatibility",
        pricing={"status": "self_hosted"},
        sort_order=140,
    ),
    catalog_item(
        provider="ollama",
        model_code="nomic-embed-text",
        display_name="Nomic Embed Text",
        model_type="embedding",
        description="Ollama 本地文本向量模型，适合私有知识库的语义检索。",
        context_window=8192,
        supports_streaming=False,
        supports_tools=False,
        supports_vision=False,
        default_base_url="http://localhost:11434/v1",
        protocol="openai_compatible",
        recommended_parameters={"dimensions": 768},
        official_url="https://docs.ollama.com/api/openai-compatibility",
        pricing={"status": "self_hosted"},
        sort_order=141,
    ),
]


async def main() -> None:
    async with SessionLocal() as db:
        await seed_model_catalog(db)
        await db.commit()


async def seed_model_catalog(db: AsyncSession) -> None:
    demo_mode = os.getenv("SEED_DEMO_MODE", "").lower() in {"1", "true", "yes"}
    items = [*REAL_CATALOG_ITEMS, *(MOCK_CATALOG_ITEMS if demo_mode else [])]
    if not demo_mode:
        await disable_demo_catalog_items(db)
    for item in items:
        result = await db.execute(
            select(ModelCatalog).where(ModelCatalog.model_code == item["model_code"])
        )
        existing = result.scalar_one_or_none()
        if existing is None:
            db.add(ModelCatalog(**item))
            continue
        for key, value in item.items():
            setattr(existing, key, value)


async def disable_demo_catalog_items(db: AsyncSession) -> None:
    for model_code in {"mock-chat", "mock-embedding"}:
        result = await db.execute(
            select(ModelCatalog).where(ModelCatalog.model_code == model_code)
        )
        existing = result.scalar_one_or_none()
        if existing is not None:
            existing.is_active = False
            existing.recommended_parameters = {
                **(existing.recommended_parameters or {}),
                "availability": "demo_only",
                "is_demo": True,
            }


if __name__ == "__main__":
    asyncio.run(main())
